### ISSUE TITLE
Enhancement: searchbar implementation

### ISSUE THREAD

**Issue by edo0** [qhungg289/startpage-eyecandy#3]
Hi!
I wanted to thank you again for you startpage, I really like it.
I made some edits to incorporate a searchbar (with code derived this[ reddit post](//www.reddit.com/r/startpages/comments/gvg79x/followed_uvallodes_tutorial_put_my_own_small_spin/fspwyct?utm_source=share&utm_medium=web2x))
If you like it, I can push the code to your repository! (else if you don't like it, I could host it on my repository - provided you were OK with that!)

![screenshot](https://user-images.githubusercontent.com/16632292/83956951-71a3a480-a863-11ea-97c0-f80b902d46d5.png)

Cheers!

**Comment by qhungg289** [comment]
This looks good! Just push the code, I will merge it.
